trigger:
- master

variables:
  sdkVersion: '5.0.402'
  nugetVersion: '6.0.0'
  solution: 'TsinghuaNet.sln'
  uwpProject: 'TsinghuaNet.XF/TsinghuaNet.XF.UWP/TsinghuaNet.XF.UWP.csproj'
  droidProject: 'TsinghuaNet.XF/TsinghuaNet.XF.Android/TsinghuaNet.XF.Android.csproj'
  iosProject: 'TsinghuaNet.XF/TsinghuaNet.XF.iOS/TsinghuaNet.XF.iOS.csproj'

jobs:
- job: Windows_XF_UWP
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: NuGetToolInstaller@0
    displayName: 'Install NuGet'
    inputs:
      versionSpec: '$(nugetVersion)'

  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      packageType: sdk
      version: '$(sdkVersion)'
      includePreviewVersions: true

  - task: MSBuild@1
    displayName: 'Build app bundle'
    inputs:
      solution: '$(uwpProject)'
      configuration: 'Release'
      msbuildArguments: '/r /p:AppxBundlePlatforms="x86|x64|arm64" /p:AppxPackageDir="..\..\build\uwp" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=SideloadOnly'
    env:
      MSBuildSDKsPath: $(Agent.ToolsDirectory)/dotnet/sdk/$(sdkVersion)/Sdks

  - pwsh: |
      rm build\uwp\*\Dependencies\Win32 -Force -Recurse
      rm build\uwp\*\Dependencies\arm -Force -Recurse
    displayName: 'Remove ARM dependencies'

  - pwsh: ls build\uwp\*\Add-AppDevPackage.resources\ -Exclude zh-CN -Attributes Directory | rm -Recurse -Force
    displayName: 'Remove other locale resources for install script'

  - task: ArchiveFiles@2
    displayName: 'Archive'
    inputs:
      rootFolderOrFile: 'build\uwp'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)\TsinghuaNet.XF.UWP.zip'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish'
    inputs:
      artifactName: 'publish'

- job: Windows_XF_Android
  pool:
    vmImage: 'windows-latest'
  variables:
    ANDROID_NDK_HOME: C:\Microsoft\AndroidNDK64\android-ndk-r16b
    ANDROID_NDK_PATH: C:\Microsoft\AndroidNDK64\android-ndk-r16b
    AndroidNdkDirectory: C:\Microsoft\AndroidNDK64\android-ndk-r16b
  steps:
  - task: NuGetToolInstaller@0
    displayName: 'Install NuGet'
    inputs:
      versionSpec: '$(nugetVersion)'

  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      packageType: sdk
      version: '$(sdkVersion)'
      includePreviewVersions: true

  - task: MSBuild@1
    displayName: 'Build apk'
    inputs:
      solution: '$(droidProject)'
      configuration: 'Release'
      platform: 'AnyCPU'
      msbuildArguments: '/r /t:SignAndroidPackage /p:JavaSdkDirectory="%JAVA_HOME_11_X64%" /p:AndroidSigningKeyPass=$(key-password) /p:AndroidSigningStorePass=$(keystore-password)'
    env:
      MSBuildSDKsPath: $(Agent.ToolsDirectory)/dotnet/sdk/$(sdkVersion)/Sdks

  - task: CopyFiles@2
    displayName: 'Publish Android Binaries'
    inputs:
      SourceFolder: $(build.sourcesdirectory)/TsinghuaNet.XF/TsinghuaNet.XF.Android/bin/Release
      Contents: '**/*-Signed.apk'
      TargetFolder: $(build.artifactstagingdirectory)
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish'
    inputs:
      artifactName: 'publish'

- job: Windows_XF_iOS
  pool:
    vmImage: 'macos-latest'
  steps:
  - task: NuGetToolInstaller@0
    displayName: 'Install NuGet'
    inputs:
      versionSpec: '$(nugetVersion)'

  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      packageType: sdk
      version: '$(sdkVersion)'
      includePreviewVersions: true

  - task: MSBuild@1
    displayName: 'Build ipa'
    inputs:
      solution: '$(iosProject)'
      configuration: 'Release'
      msbuildArguments: '/r /p:BuildIpa=true /p:IpaPackageDir=$(build.artifactstagingdirectory) /p:CodesignEntitlements=""'
    env:
      MSBuildSDKsPath: $(Agent.ToolsDirectory)/dotnet/sdk/$(sdkVersion)/Sdks

  - task: PublishBuildArtifacts@1
    displayName: 'Publish'
    inputs:
      artifactName: 'publish'
