# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  cliProject: 'TsinghuaNet.CLI/TsinghuaNet.CLI.csproj"'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: "3.0.100-preview6-012264"

- task: DotNetCoreCLI@2
  inputs:
    projects: '$(cliProject)'
    command: restore

- task: DotNetCoreCLI@2
  inputs:
    projects: '$(cliProject)'
    command: build
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    projects: '$(cliProject)'
    command: publish
    configuration: '$(buildConfiguration)'
    arguments: '-r win-x64'
