namespace TsinghuaNetHelper
{
    runtimeclass BackgroundHelper
    {
        static Windows.Foundation.IAsyncOperation<Boolean> RequestAccessAsync();

        static void RegisterLiveTile(Boolean reg);
        static void RegisterLogin(Boolean reg);
    }

    [default_interface] runtimeclass LiveTileTask : Windows.ApplicationModel.Background.IBackgroundTask
    {
        LiveTileTask();
    }

    [default_interface] runtimeclass LoginTask : Windows.ApplicationModel.Background.IBackgroundTask
    {
        LoginTask();
    }
} // namespace TsinghuaNetHelper
