import "NetHelper.idl";
import "SettingsHelper.idl";

namespace TsinghuaNetHelper
{
    runtimeclass BackgroundHelper
    {
        static Windows.Foundation.IAsyncOperation<Boolean> RequestAccessAsync();

        static void RegisterLiveTile(Boolean reg);
        static void RegisterLogin(Boolean reg);
    }

    runtimeclass ConnectHelper
    {
        static NetState GetSuggestNetState(SettingsHelper settings);
        static IConnect GetHelper(NetState state);
        static IConnect GetHelper(NetState state, String username, String password);
    }
} // namespace TsinghuaNetHelper
