import "SettingsHelper.idl";

namespace TsinghuaNetHelper
{
    [bindable] runtimeclass FluxUser : Windows.UI.Xaml.DependencyObject
    {
        FluxUser();

        String Username;
        static Windows.UI.Xaml.DependencyProperty UsernameProperty { get; };

        UInt64 Flux;
        static Windows.UI.Xaml.DependencyProperty FluxProperty { get; };

        Windows.Foundation.TimeSpan OnlineTime;
        static Windows.UI.Xaml.DependencyProperty OnlineTimeProperty { get; };

        Double Balance;
        static Windows.UI.Xaml.DependencyProperty BalanceProperty { get; };
    };

    struct LogResponse
    {
        String Code;
        String Message;
    };

    interface ICredential
    {
        String Username;
        String Password;
    }

    interface IConnect
    {
        Windows.Foundation.IAsyncOperation<LogResponse> LoginAsync();
        Windows.Foundation.IAsyncOperation<LogResponse> LogoutAsync();
        Windows.Foundation.IAsyncOperation<FluxUser> FluxAsync();
    }

    runtimeclass ConnectHelper
    {
        static IConnect GetHelper(NetState state);
        static IConnect GetHelper(NetState state, String username, String password);
    }

    runtimeclass NetHelper : ICredential, IConnect
    {
        NetHelper();
    }

    runtimeclass Auth4Helper : ICredential, IConnect
    {
        Auth4Helper();
    }

    runtimeclass Auth6Helper : ICredential, IConnect
    {
        Auth6Helper();
    }

    runtimeclass Auth4Helper25 : ICredential, IConnect
    {
        Auth4Helper25();
    }

    runtimeclass Auth6Helper25 : ICredential, IConnect
    {
        Auth6Helper25();
    }

    [bindable] runtimeclass NetUser : Windows.UI.Xaml.DependencyObject
    {
        NetUser();

        String Address;
        static Windows.UI.Xaml.DependencyProperty AddressProperty { get; };

        String LoginTime;
        static Windows.UI.Xaml.DependencyProperty LoginTimeProperty { get; };

        String Client;
        static Windows.UI.Xaml.DependencyProperty ClientProperty { get; };

        void Drop();
        event Windows.Foundation.EventHandler<String> DropUser;

        Boolean Equals(NetUser user);
    }

    runtimeclass UseregHelper : ICredential
    {
        UseregHelper();

        Windows.Foundation.IAsyncOperation<LogResponse> LoginAsync();
        Windows.Foundation.IAsyncOperation<LogResponse> LogoutAsync();
        Windows.Foundation.IAsyncOperation<LogResponse> LogoutAsync(String ip);
        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVector<NetUser> > UsersAsync();
    }
} // namespace TsinghuaNetHelper
