import "NetHelper.idl";
import "SettingsHelper.idl";

namespace TsinghuaNetHelper
{
    runtimeclass UserHelper
    {
        static String GetFluxString(UInt64 flux);
        static String GetTimeSpanString(Windows.Foundation.TimeSpan time);
        static String GetCurrencyString(Double currency);
        static String GetNetStateString(NetState state);
        static String GetInternetStatusString(InternetStatus status);
        static UInt64 GetMaxFlux(FluxUser user);
        static FluxUser GetFluxUser(String str);
        static LogResponse GetLogResponse(String str);
        static LogResponse GetAuthLogResponse(String str, Boolean login);
        static String GetResponseString(LogResponse response);
    }

    runtimeclass NotificationHelper
    {
        static void UpdateTile(FluxUser user);
        static void SendToast(FluxUser user);
    }
} // namespace TsinghuaNetHelper
