namespace TsinghuaNetHelper
{
    enum NetState
    {
        Unknown,
        Auth4,
        Auth6,
        Net,
        Auth4_25,
        Auth6_25,
        Direct
    };

    enum InternetStatus
    {
        Unknown,
        None,
        Wwan,
        Wlan,
        Lan
    };

    runtimeclass CredentialHelper
    {
        static String GetCredential(String username);
        static void SaveCredential(String username, String password);
        static void RemoveCredential(String username);
    }

    runtimeclass SettingsHelper
    {
        SettingsHelper();

        String StoredUsername;
        Boolean AutoLogin;
        Boolean BackgroundAutoLogin;
        Boolean BackgroundLiveTile;
        NetState LanState;
        NetState WwanState;
        NetState WlanState(String ssid);
        void WlanState(String ssid, NetState state);

        Boolean InternetAvailable();
        InternetStatus InternetStatus(out String ssid);
    }
} // namespace TsinghuaNetHelper
