namespace TsinghuaNetBackground
{
    [default_interface] runtimeclass LoginTask : Windows.ApplicationModel.Background.IBackgroundTask
    {
        LoginTask();
    }
} // namespace TsinghuaNetBackground
