namespace TsinghuaNetUWP
{
    [bindable][default_interface] runtimeclass Arc : Windows.UI.Xaml.Controls.Canvas
    {
        Arc();

        Double Thickness;
        static Windows.UI.Xaml.DependencyProperty ThicknessProperty { get; };

        Windows.UI.Xaml.Media.Brush Fill;
        static Windows.UI.Xaml.DependencyProperty FillProperty { get; };

        Double Value;
        static Windows.UI.Xaml.DependencyProperty ValueProperty { get; };
    }
} // namespace TsinghuaNetUWP
