namespace TsinghuaNetUWP
{
    runtimeclass NetStateCheckedConverter : Windows.UI.Xaml.Data.IValueConverter
    {
        NetStateCheckedConverter();
    }

    runtimeclass ThemeCheckedConverter : Windows.UI.Xaml.Data.IValueConverter
    {
        ThemeCheckedConverter();
    }
} // namespace TsinghuaNetUWP
