import "SsidSuggestion.idl";

namespace TsinghuaNetUWP
{
    [default_interface] runtimeclass NetStateCheckedConverter : Windows.UI.Xaml.Data.IValueConverter
    {
        NetStateCheckedConverter();
    }

    [default_interface] runtimeclass ThemeCheckedConverter : Windows.UI.Xaml.Data.IValueConverter
    {
        ThemeCheckedConverter();
    }

    [default_interface] runtimeclass UserContentTypeCheckedConverter : Windows.UI.Xaml.Data.IValueConverter
    {
        UserContentTypeCheckedConverter();
    }

    [default_interface] runtimeclass NetStateIndexConverter : Windows.UI.Xaml.Data.IValueConverter
    {
        NetStateIndexConverter();
    }
} // namespace TsinghuaNetUWP
