import "SsidSuggestion.idl";

namespace TsinghuaNetUWP
{
    [default_interface] runtimeclass EditSuggestionDialog : Windows.UI.Xaml.Controls.ContentDialog
    {
        EditSuggestionDialog();
        SsidSuggestion LanCombo { get; };
        SsidSuggestion WwanCombo { get; };
    }
} // namespace TsinghuaNetUWP
