namespace TsinghuaNetUWP
{
    [default_interface] runtimeclass EditSuggestionDialog : Windows.UI.Xaml.Controls.ContentDialog
    {
        EditSuggestionDialog();
    }
} // namespace TsinghuaNetUWP
