namespace TsinghuaNetUWP
{
    [bindable] runtimeclass FluxUserBox : Windows.UI.Xaml.DependencyObject
    {
        FluxUserBox();
        FluxUserBox(TsinghuaNetHelper.FluxUser flux);

        String Username;
        static Windows.UI.Xaml.DependencyProperty UsernameProperty { get; };

        UInt64 Flux;
        static Windows.UI.Xaml.DependencyProperty FluxProperty { get; };

        Windows.Foundation.TimeSpan OnlineTime;
        static Windows.UI.Xaml.DependencyProperty OnlineTimeProperty { get; };

        Double Balance;
        static Windows.UI.Xaml.DependencyProperty BalanceProperty { get; };
    }
} // namespace TsinghuaNetUWP
