namespace TsinghuaNetUWP
{
    interface IUserContent
    {
        TsinghuaNetHelper.FluxUser User;
        Windows.Foundation.TimeSpan OnlineTime;
        Double FreeOffset;
        Double FluxOffset;

        Boolean IsProgressActive;
        void BeginAnimation();
        Boolean AddOneSecond();
    }
} // namespace TsinghuaNetUWP
