import "IUserContent.idl";

namespace TsinghuaNetUWP
{
    [default_interface] runtimeclass LineUserContent : Windows.UI.Xaml.Controls.UserControl, IUserContent
    {
        LineUserContent();

        Double Max(Double d1, Double d2);

        static Windows.UI.Xaml.DependencyProperty UserProperty { get; };
        static Windows.UI.Xaml.DependencyProperty OnlineTimeProperty { get; };
        static Windows.UI.Xaml.DependencyProperty FreeOffsetProperty { get; };
        static Windows.UI.Xaml.DependencyProperty FluxOffsetProperty { get; };
    }
} // namespace TsinghuaNetUWP
