import "MainViewModel.idl";
import "Arc.idl";

namespace TsinghuaNetUWP
{
    [default_interface] runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
    {
        MainPage();
        MainViewModel Model { get; };
        Windows.UI.Xaml.Media.Animation.Storyboard FluxStoryboard { get; };
    }
} // namespace TsinghuaNetUWP
