import "IUserContent.idl";

namespace TsinghuaNetUWP
{
    [bindable][default_interface] runtimeclass MainViewModel : Windows.UI.Xaml.DependencyObject
    {
        MainViewModel();

        Windows.UI.Xaml.UIElement UserContent;
        static Windows.UI.Xaml.DependencyProperty UserContentProperty { get; };

        TsinghuaNetHelper.LogResponse Response;
        static Windows.UI.Xaml.DependencyProperty ResponseProperty { get; };

        String Username;
        static Windows.UI.Xaml.DependencyProperty UsernameProperty { get; };

        String Password;
        static Windows.UI.Xaml.DependencyProperty PasswordProperty { get; };

        TsinghuaNetHelper.NetState State;
        static Windows.UI.Xaml.DependencyProperty StateProperty { get; };

        Boolean AutoLogin;
        static Windows.UI.Xaml.DependencyProperty AutoLoginProperty { get; };
        event Windows.Foundation.EventHandler<Boolean> AutoLoginChanged;

        Boolean BackgroundAutoLogin;
        static Windows.UI.Xaml.DependencyProperty BackgroundAutoLoginProperty { get; };
        event Windows.Foundation.EventHandler<Boolean> BackgroundAutoLoginChanged;

        Boolean BackgroundLiveTile;
        static Windows.UI.Xaml.DependencyProperty BackgroundLiveTileProperty { get; };
        event Windows.Foundation.EventHandler<Boolean> BackgroundLiveTileChanged;

        TsinghuaNetHelper.InternetStatus NetStatus;
        static Windows.UI.Xaml.DependencyProperty NetStatusProperty { get; };

        String Ssid;
        static Windows.UI.Xaml.DependencyProperty SsidProperty { get; };

        TsinghuaNetHelper.NetState SuggestState;
        static Windows.UI.Xaml.DependencyProperty SuggestStateProperty { get; };

        Windows.Foundation.Collections.IObservableVector<Object> NetUsers { get; };

        Windows.UI.Xaml.ElementTheme Theme;
        static Windows.UI.Xaml.DependencyProperty ThemeProperty { get; };

        UserContentType ContentType;
        static Windows.UI.Xaml.DependencyProperty ContentTypeProperty { get; };
    }
} // namespace TsinghuaNetUWP
