namespace TsinghuaNetUWP
{
    [bindable][default_interface] runtimeclass MainViewModel : Windows.UI.Xaml.DependencyObject
    {
        MainViewModel();

        String OnlineUser;
        static Windows.UI.Xaml.DependencyProperty OnlineUserProperty { get; };

        UInt64 Flux;
        static Windows.UI.Xaml.DependencyProperty FluxProperty { get; };

        Windows.Foundation.TimeSpan OnlineTime;
        static Windows.UI.Xaml.DependencyProperty OnlineTimeProperty { get; };

        Double Balance;
        static Windows.UI.Xaml.DependencyProperty BalanceProperty { get; };

        Double FluxPercent;
        static Windows.UI.Xaml.DependencyProperty FluxPercentProperty { get; };

        Double FreePercent;
        static Windows.UI.Xaml.DependencyProperty FreePercentProperty { get; };

        String Username;
        static Windows.UI.Xaml.DependencyProperty UsernameProperty { get; };

        String Password;
        static Windows.UI.Xaml.DependencyProperty PasswordProperty { get; };

        Windows.Foundation.IReference<Boolean> AutoLogin;
        static Windows.UI.Xaml.DependencyProperty AutoLoginProperty { get; };
        event Windows.Foundation.EventHandler<Windows.Foundation.IReference<Boolean> > AutoLoginChanged;

        TsinghuaNetHelper.InternetStatus NetStatus;
        static Windows.UI.Xaml.DependencyProperty NetStatusProperty { get; };

        String Ssid;
        static Windows.UI.Xaml.DependencyProperty SsidProperty { get; };

        TsinghuaNetHelper.NetState SuggestState;
        static Windows.UI.Xaml.DependencyProperty SuggestStateProperty { get; };

        Windows.Foundation.Collections.IObservableVector<IInspectable> NetUsers { get; };

        TsinghuaNetHelper.NetState State;
        void SyncState(TsinghuaNetHelper.NetState value);
        event Windows.Foundation.EventHandler<TsinghuaNetHelper.NetState> StateChanged;
    }
} // namespace TsinghuaNetUWP
