namespace TsinghuaNetUWP
{
    runtimeclass NetStateBox
    {
        NetStateBox();
        NetStateBox(TsinghuaNetHelper.NetState state);

        TsinghuaNetHelper.NetState Value;
    }
} // namespace TsinghuaNetUWP
