namespace TsinghuaNetUWP
{
    runtimeclass NetStateSsidBox : Windows.UI.Xaml.DependencyObject
    {
        NetStateSsidBox();

        String Ssid;
        TsinghuaNetHelper.NetState Value;
    }
} // namespace TsinghuaNetUWP
