namespace TsinghuaNetUWP
{
    [default_interface] runtimeclass NetStateSsidBox : Windows.UI.Xaml.DependencyObject
    {
        NetStateSsidBox();

        String Ssid;
        Int32 Value;
    }
} // namespace TsinghuaNetUWP
