namespace TsinghuaNetUWP
{
    [bindable] runtimeclass NetUserModel : Windows.UI.Xaml.DependencyObject
    {
        NetUserModel();

        String Address;
        static Windows.UI.Xaml.DependencyProperty AddressProperty { get; };

        String LoginTime;
        static Windows.UI.Xaml.DependencyProperty LoginTimeProperty { get; };

        String Client;
        static Windows.UI.Xaml.DependencyProperty ClientProperty { get; };
    }
} // namespace TsinghuaNetUWP
