namespace TsinghuaNetUWP
{
    [bindable][default_interface] runtimeclass SsidSuggestion : Windows.UI.Xaml.Controls.StackPanel
    {
        SsidSuggestion();

        String Ssid;
        static Windows.UI.Xaml.DependencyProperty SsidProperty { get; };

        TsinghuaNetHelper.NetState Value;
        static Windows.UI.Xaml.DependencyProperty ValueProperty { get; };

        Windows.UI.Xaml.Style SsidStyle;
        static Windows.UI.Xaml.DependencyProperty SsidStyleProperty { get; };

        Windows.Foundation.Collections.IObservableVector<Object> States { get; };

        Int32 ValueToIndex(TsinghuaNetHelper.NetState value);
        TsinghuaNetHelper.NetState IndexToValue(Int32 index);
    }
} // namespace TsinghuaNetUWP
