namespace TsinghuaNetUWP
{
    [bindable][default_interface] runtimeclass SsidSuggestion : Windows.UI.Xaml.Controls.StackPanel
    {
        SsidSuggestion();

        String Ssid;
        static Windows.UI.Xaml.DependencyProperty SsidProperty { get; };

        Int32 Value;
        static Windows.UI.Xaml.DependencyProperty ValueProperty { get; };

        Windows.UI.Xaml.Style SsidStyle;
        static Windows.UI.Xaml.DependencyProperty SsidStyleProperty { get; };

        Windows.Foundation.Collections.IObservableVector<Object> States { get; };
    }
} // namespace TsinghuaNetUWP
